name: 🤝 Become a Partner
description: Become a Partner
title: "[PARTNER] {{ Company name }} "
labels: ['Partner/new-Partner, untriaged']
projects: ["testProject/Partners"]



body:
  - type: markdown
    attributes:
      value: "# Become a Partner! 🎉"
  - type: markdown
    attributes:
      value: |
        Please take the time to fill out this new partner request.
        We will review your submission and get back to you as soon as possible.


  
  - type: input
    attributes:
      label: Organization Name
      description: Please let us know the exact business name
      placeholder: Example Inc.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Business description
      description: A clear and concise description of your business. We will use this to help create your partner page.
      placeholder: We are a ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Product description
      description: A clear and concise description of your product(s) and/or services offered to the OpenSearch community.
      placeholder: We offer ...
    validations:
      required: false
  - type: input
    attributes:
      label: URL 
      description: Please provide the URL to your organization's website.
      placeholder: https://www.example.com
    validations:
      required: true

  - type: input
    attributes:
      label: Contact Email
      placeholder: Info@example.com (Where can customers contact you?)
    validations:
      required: true
  - type: input
    attributes:
      label: Contact Phone
      placeholder: (xxx) xxx-xxxx (Where can customers contact you?)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Main office location
      description: Main office location or address (if applicable)
      placeholder: City, Country
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: Regions Served
      description: What regions of the world do you serve?
      # multiple: true
      options:
        - Global
        - North America
        - South America
        - Europe
        - Asia Pacific
        - Middle East
        - Africa
        - Australia
    default: Global
    # validations:
    #   required: true
  
  
  # - type: markdown
  #   attributes:
  #     value: "# Internal Contact Information"
  # - type: markdown
  #   attributes:
  #     value: |
  #       Who should we reach out to in case we need help updating your companies profile? 
  #       This information is not displayed on the site and never shared with the public.

  # - type: input
  #   attributes:
  #     label: Name
  #     placeholder: Jon Smith
  #   validations:
  #     required: true
  # - type: input
  #   attributes:
  #     label: Email
  #     placeholder: JonSmith@example.com
  #   validations:
  #     required: true




  # - type: dropdown
  #   attributes:
  #     label: OpenSearch Specialty 
  #     description: Where can customers contact you? 
  #     placeholder: Info@example.com
  #   validations:
  #     required: true


  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  


  - type: textarea
    attributes:
      label: Additional Details
      description: Add any other context about the problem here.
      value: |
        **Plugins**
        Please list all plugins currently enabled.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

        **Host/Environment (please complete the following information):**
         - OS: [e.g. iOS]
         - Version [e.g. 22]

        **Additional context**
        Add any other context about the problem here.
    validations:
      required: false