name: 🤝 Partner page information
description: Become an OpenSearch Partner
title: "[PARTNER] <title>"
labels: ['Partner/new-Partner, untriaged']
projects: ["testProject/Partners"]



body:
  - type: markdown
    attributes:
      value: "## Thank you for becoming an OpenSearch Partner! 🎉"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new partner request.
        We will review your submission and get back to you as soon as possible.
  
  - type: input
    attributes:
      label: Organization Name
      description: Please let us know the exact business name
      placeholder: Example Inc.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Business description
      description: A clear and concise description of your business. We will use this to help create your partner page.
      placeholder: We are a ...
    validations:
      required: true

  - type: input
    attributes:
      label: URL 
      description: Please provide the URL to your organization's website.
      placeholder: https://www.example.com
    validations:
      required: true

  - type: input
    attributes:
      label: Contact Email
      description: Where can customers contact you? 
      placeholder: Info@example.com
    validations:
      required: true

  - type: textarea
    attributes:
      label: Name of relevant product(s) or service for OpenSearch audience
      description: A clear and concise description of your product(s) and/or services offered to the OpenSearch community.
      placeholder: We offer...
    validations:
      required: true

  # - type: dropdown
  #   attributes:
  #     label: OpenSearch Specialty 
  #     description: Where can customers contact you? 
  #     placeholder: Info@example.com
  #   validations:
  #     required: true


  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  


  - type: textarea
    attributes:
      label: Additional Details
      description: Add any other context about the problem here.
      value: |
        **Plugins**
        Please list all plugins currently enabled.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

        **Host/Environment (please complete the following information):**
         - OS: [e.g. iOS]
         - Version [e.g. 22]

        **Additional context**
        Add any other context about the problem here.
    validations:
      required: false